# This is a basic workflow to help you get started with Actions

name: DOCKER TEST CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Docker build for me 
        run: |
          echo Building your docker image 
          docker build -t flask-image .
      - name: Docker run container and test 
        run: |
          docker run -d -p 5000:5000 flask-image
      - name: Enable TCP on port 5000
        run: sudo ufw allow 5000/tcp
      
      - name: Testing the container
        run: |
          curl localhost:5000  
